"""BM25 retrieval over chunked filing text (architecture.md §5).

Cell B of the strategy grid chunks the whole filing into ~800-token windows and retrieves
the top-8 for a KPI-specific query with Okapi BM25 (`rank_bm25`). BM25 over embeddings is
deliberate: deterministic, dependency-light, and retrieval quality is not the object of
study (limitation (f)). Chunking uses whitespace-token windows — a stable proxy for the
~800-token budget that needs no tokenizer and reproduces exactly.
"""

from __future__ import annotations

import re

from pydantic import BaseModel
from rank_bm25 import BM25Okapi

# Frozen KPI -> retrieval query. Natural-language terms a filer uses for each line item;
# BM25 needs no exact phrasing, just the discriminating tokens.
KPI_QUERIES: dict[str, str] = {
    "revenue": "total revenue net sales total net sales",
    "net_income": "net income net earnings",
    "eps_diluted": "diluted earnings per share diluted eps",
    "total_assets": "total assets",
    "operating_cash_flow": "cash generated by operating activities net cash provided by operating",
}

DEFAULT_CHUNK_TOKENS = 800
DEFAULT_TOP_K = 8

_TOKEN = re.compile(r"[a-z0-9]+")


def _tokenize(s: str) -> list[str]:
    return _TOKEN.findall(s.lower())


class Chunk(BaseModel):
    index: int
    text: str


def chunk_text(text: str, chunk_tokens: int = DEFAULT_CHUNK_TOKENS) -> list[Chunk]:
    """Split filing text into non-overlapping ~``chunk_tokens``-word windows.

    Whitespace words stand in for tokens: deterministic and tokenizer-free. Chunk text
    preserves the original words joined by single spaces (BM25 ignores layout anyway).
    """
    words = text.split()
    chunks: list[Chunk] = []
    for i in range(0, len(words), chunk_tokens):
        window = words[i : i + chunk_tokens]
        chunks.append(Chunk(index=len(chunks), text=" ".join(window)))
    return chunks


def retrieve(
    text: str,
    query: str,
    top_k: int = DEFAULT_TOP_K,
    chunk_tokens: int = DEFAULT_CHUNK_TOKENS,
) -> list[Chunk]:
    """Return the top-``top_k`` chunks for ``query``, most relevant first.

    Deterministic: ties in BM25 score break by ascending chunk index, so the same filing
    and query always yield the same ordered chunks.
    """
    chunks = chunk_text(text, chunk_tokens)
    if not chunks:
        return []
    corpus = [_tokenize(c.text) for c in chunks]
    bm25 = BM25Okapi(corpus)
    scores = bm25.get_scores(_tokenize(query))
    order = sorted(range(len(chunks)), key=lambda i: (-scores[i], i))
    return [chunks[i] for i in order[:top_k]]


def retrieve_for_kpi(
    text: str, kpi: str, top_k: int = DEFAULT_TOP_K, chunk_tokens: int = DEFAULT_CHUNK_TOKENS
) -> list[Chunk]:
    """Retrieve the top chunks for a KPI using its frozen query."""
    if kpi not in KPI_QUERIES:
        raise KeyError(f"no retrieval query for KPI {kpi!r}")
    return retrieve(text, KPI_QUERIES[kpi], top_k=top_k, chunk_tokens=chunk_tokens)
